# Sử dụng Node.js làm base image
FROM node:16

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và cài đặt dependencies
COPY package*.json ./
RUN npm install


# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Chạy React trên cổng 3001
ENV PORT=3001

# Build static files (nếu production)
RUN npm run build

# Expose cổng frontend (3000)
EXPOSE 3001

# Chạy ứng dụng frontend
CMD ["npm", "start"]
